# Generated by Django 2.1.7 on 2019-03-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
        migrations.AddField(
            model_name='book',
            name='document',
            field=models.FileField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
